### ISSUE TITLE
Add rights-statement specific validation

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/rac_schemas#25]
## Is your feature request related to a problem? Please describe.
We need better tests for validation of rights statements.

## Describe the solution you'd like
Add a rights statement schema and valid/invalid fixtures so that unit tests perform validation on rights statements. This should include source_rights_statements, right_statements and rights_granted.

**Comment by helrond** [comment]
Among other things, it appears that many of the enums in these objects are not actually being activated because they are nested in an `items` key.

**Comment by p-galligan** [comment]
@bonniegee @helrond Rather than completely rebuilding the PREMIS rights section in JSON schema, I've been looking at what we use for Rights Shells and Rights Granted in the Aquila models. Is that fine for this? There are a lot of additional fields in PREMIS and conditional complexity based on basis types.

**Comment by helrond** [comment]
I think a draft PR would help me answer this question more definitively, but I do think there is some nuance in PREMIS we want to capture. For the different basis types and required fields, would it be possible to use a `oneOf` and then have a different validation object for each basis type?
